AXIS_UP ignore
AXIS_DOWN ignore
AXIS_RIGHT ignore
AXIS_LEFT ignore
UP add volume 2
DOWN add volume -2
Shift+RIGHT frame-step
Shift+LEFT frame-back-step
Shift+UP add volume 10
Shift+DOWN add volume -10
y cycle deband
z cycle deband
ctrl+d vf toggle yadif
x add sub-delay +0.042
c add sub-delay -0.042
b add audio-delay +0.042
n add audio-delay -0.042
a cycle-values video-aspect "16:9" "4:3" "2.35:1" "-1"
KP_ADD add speed 0.1
KP_SUBTRACT add speed -0.1
Q     script-binding quality_menu/video_formats_toggle #! Stream Quality > Video
q     script-binding quality_menu/video_formats_toggle #! Stream Quality > Video
Alt+q script-binding quality_menu/audio_formats_toggle #! Stream Quality > Audio
Ctrl+r script-binding quality_menu/reload
Ctrl+c script-message copy-to-clipboard
l run /home/riwxr/scripts/mpv_window_jankryyy.sh
Shift+l run /home/riwxr/scripts/mpv_window_jankryyy.sh
Alt+l ab-loop #set/clear A-B loop points
Shift+o run /home/riwxr/scripts/qutebrowser/dmenu.sh
Alt+h run /home/riwxr/scripts/qutebrowser/history_mpv_play.sh
