# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

# potentially fixing fullscreeen
# vo=dmabuf-wayland
target-colorspace-hint=no

# set default speed 6
speed=1.6

# volume default 85
volume=85

# pause at start
pause=yes

# cache videos and try to preload 60s ahead
cache=yes
cache-pause=no
demuxer-max-bytes=1GiB
demuxer-readahead-secs=60

# preload playlist
prefetch-playlist=yes

