-- main/autoStart.lua
local x = require("main.globalVariables")

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("~/.config/hypr/autostart.sh")
	hl.exec_cmd("kdeconnectd & kdeconnect-indicator")
	hl.exec_cmd("swaync & hypridle & flameshot & hyprsunset & swayosd-server & squeekboard")
	hl.exec_cmd("hyprctl setcursor Nordzy 29")
	hl.exec_cmd("copyq --start-server")
	hl.exec_cmd("bash ~/scripts/battery_alert.sh")
	hl.exec_cmd("awww-daemon & awww img " .. x.wallpaper)
	hl.exec_cmd("mpd ~/.config/mpd/mpd.conf")
	hl.exec_cmd("ydotoold")
	hl.exec_cmd("elephant")
	hl.exec_cmd("hyprscratch init clean eager spotless")
	hl.exec_cmd("qs -p ~/.config/quickshell/clock/shell.qml -d")
	hl.exec_cmd("qs -p '/home/riwxr/dotfiles/.config/quickshell/idealshell/shell.qml' -d")
	hl.exec_cmd("qs -p ~/.config/quickshell/dim/dimshell.qml -d")
	hl.exec_cmd("qs -p ~/.config/quickshell/clock/tinytime.qml -d")
	hl.exec_cmd("controlloid-server")
	hl.exec_cmd("zapzap")
	hl.exec_cmd("geary --gapplication-service")
end)

hl.on("hyprland.shutdown", function()
	os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
	hl.exec_cmd("notify-send 'bye~~'")
end)
